#!/bin/bash

# tvloop help and usage functionality

show_usage() {
    local script_name="${1:-tvloop}"
    local channels_dir="${2:-$PROJECT_ROOT/channels}"
    
    echo "🎬 tvloop - 24-Hour Video Channel System"
    echo ""
    echo "Usage: $script_name <command> [options]"
    echo ""
    echo "Commands:"
    echo "  create <type> <name> [source] [hours] [--force] - Create a new channel"
    echo "                             type: youtube"
    echo "                             name: channel name"
    echo "                             source: YouTube URL or @username"
    echo "                             hours: target duration (default: 24)"
    echo "                             --force: recreate existing channel"
    echo "  tune <player> [channel]  - Tune in to a channel"
    echo "                             player: mpv"
    echo "                             channel: optional, uses first available if not specified"
    echo "                             Note: mpv supports hotkey channel switching (1-9 keys)"
    echo "  status [channel]         - Show channel status"
    echo "                             channel: optional, shows first channel if not specified"
    echo "  list                     - List all available channels"
    echo "  remove <channel>         - Remove a channel"
    echo "                             channel: name of channel to remove"
    echo "  help                     - Show this help message"
    echo ""
    echo "Examples:"
    echo "  $script_name create youtube jovem_nerd https://www.youtube.com/@JovemNerd 2"
    echo "  $script_name create youtube existing_channel https://www.youtube.com/@JovemNerd 2 --force"
    echo "  $script_name tune mpv              - Tune in to first channel with mpv"
    echo "  $script_name status                - Show status of first channel"
    echo "  $script_name remove my_channel     - Remove a channel"
    echo ""
    echo "Channel Switching (MPV only):"
    echo "  Press 1-9 to switch channels while playing"
    echo "  Press 'i' to show channel information"
    echo "  $script_name list                  - List all channels"
    echo ""
    echo "Channel Directory: $channels_dir"
}
