#!/bin/bash

# YouTube Channel Usage Information
# Usage and help functions for YouTube channel creation

show_youtube_channel_usage() {
    echo "🎬 YouTube Channel Creator for tvloop (yt-dlp version)"
    echo ""
    echo "Usage: $0 <channel_name> <youtube_channel> [target_hours] [auto_start] [quality]"
    echo ""
    echo "Parameters:"
    echo "  channel_name     - Name for the new channel (e.g., 'jovem_nerd', 'tech_channel')"
    echo "  youtube_channel  - YouTube channel (URL, @username, or channel ID)"
    echo "  target_hours     - Target duration in hours (default: 24)"
    echo "  auto_start       - 'true' to start playing immediately (optional)"
    echo "  quality          - Video quality (default: 232,609 for 720p)"
    echo ""
    echo "Quality Options:"
    echo "  230,605          - 360p (fastest, for testing)"
    echo "  231,606          - 480p (fast)"
    echo "  232,609          - 720p (balanced, default)"
    echo "  270,614,616      - 1080p (high quality, slower)"
    echo "  best             - Best available quality"
    echo "  worst            - Worst quality (fastest)"
    echo ""
    echo "YouTube Channel Formats:"
    echo "  - Channel URL: https://www.youtube.com/@JovemNerd"
    echo "  - Username: @JovemNerd"
    echo "  - Channel ID: UC..."
    echo ""
    echo "Examples:"
    echo "  $0 jovem_nerd https://www.youtube.com/@JovemNerd"
    echo "  $0 tech_channel @JovemNerd 12"
    echo "  $0 gaming_channel UC1234567890 48 true"
    echo "  $0 fast_channel @JovemNerd 1 false 230,605"
    echo "  $0 hd_channel @JovemNerd 24 false 232,609"
    echo ""
    echo "This script will:"
    echo "  1. Create channel directory"
    echo "  2. Fetch videos from YouTube channel using yt-dlp"
    echo "  3. Create 24-hour playlist automatically"
    echo "  4. Initialize channel with timing"
    echo "  5. Start playing (if auto_start=true)"
    echo ""
    echo "No API key required! Uses yt-dlp for direct YouTube access."
}
